<?php
	define("DB_SERVER","localhost");
	#define("DB_USER","u2coding");
	define("DB_USER","root");
	define("DB_PWD","");
	#define("DB_PWD","Firewall12!");
	define("DB_NAME","SFYC");
	define("USER_TABLE","users");
	define("RELATION_TABLE","relation");
	define("PET_TABLE","pet");
?>